"""Memory storage logic for remember command.

Handles adding decisions and context to the memory system.
"""

from datetime import datetime

from sqlalchemy import insert

from jarvis.memory.core import (
    get_chroma_client,
    get_sqlite_engine,
    semantic_memory,
)


def add_decision(project_path: str, content: str) -> dict:
    """Add a decision to semantic memory.

    Stores decision in both SQLite (metadata) and ChromaDB (embeddings).

    Args:
        project_path: Path to project root
        content: Decision content to remember

    Returns:
        Dictionary with status and new entry ID
    """
    # Get timestamp
    timestamp = datetime.now().isoformat()

    # Store in SQLite
    engine = get_sqlite_engine(project_path)
    with engine.connect() as conn:
        result = conn.execute(
            insert(semantic_memory).values(content=content, timestamp=timestamp)
        )
        conn.commit()
        new_id = result.lastrowid

    # Store in ChromaDB for semantic search
    client = get_chroma_client(project_path)
    collection = client.get_or_create_collection("decisions")  # type: ignore[attr-defined]

    # For now, use content as document (embedding will be generated by ChromaDB)
    # In future, we'll use bge-large-en-v1.5 for custom embeddings
    collection.add(
        documents=[content],
        metadatas=[{"timestamp": timestamp, "type": "decision"}],
        ids=[f"decision_{new_id}"],
    )

    return {"status": "success", "id": new_id, "timestamp": timestamp}
